- name: Frontend Setup
  hosts: all
  tasks:
    - name: Disable default nginx
      ansible.builtin.shell: dnf module disable nginx -y

    - name: Enable Nginx 24
        ansible.builtin.shell: dnf module enable nginx:1.24 -y

    - name: Install nginx
        ansible.builtin.dnf:
          name: nginx
          state: installed
